# Generated by Django 5.2.6 on 2025-09-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view', 'Can view books'), ('can_create', 'Can create books'), ('can_edit', 'Can edit books'), ('can_delete', 'Can delete books'))},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
