# Generated by hand to align follow relationship changes

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='followers',
            new_name='following',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(
                blank=True,
                help_text='Users this user is following',
                related_name='followers',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
