"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r^cxv)+2uyv^iv!1ay2+-9&b6ufp#@7qz3$_*=k#y475(r1e@h'

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable DJANGO_DEBUG to toggle debug (default True for local dev)
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

# In production, set DJANGO_ALLOWED_HOSTS to a comma-separated list of hosts
ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()] or []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Custom CSP header middleware (see bookshelf/middleware.py)
    'bookshelf.middleware.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# After successful login, redirect users here by default
LOGIN_REDIRECT_URL = '/books/'
LOGIN_URL = '/accounts/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use custom user model from bookshelf app
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Media files (for profile photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------
# Security hardening (prod)
# -------------------------
# These settings help protect against common web vulnerabilities. They are
# enforced by default when DEBUG=False. You can still override them via env
# variables for special cases (e.g., local dev behind HTTPS).

# Force HTTPS by default in production. Override with DJANGO_SECURE_SSL_REDIRECT.
# - Default: True when DEBUG=False, else False (so local HTTP works by default).
SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', str(not DEBUG)).lower() == 'true'

# HTTP Strict Transport Security (HSTS)
# - Only enable when your site is accessible via HTTPS (commonly always in prod).
# - Default: 31536000 (1 year) when DEBUG=False, else 0 (disabled in dev).
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True' if not DEBUG else 'False'
).lower() == 'true'
SECURE_HSTS_PRELOAD = os.getenv('DJANGO_SECURE_HSTS_PRELOAD', 'True' if not DEBUG else 'False').lower() == 'true'

# Reverse proxy SSL termination support (e.g., Nginx/Apache terminating TLS).
# If your proxy sets X-Forwarded-Proto: https, set the header below so Django
# considers the request secure. Configure via env as a comma-separated pair,
# e.g. DJANGO_SECURE_PROXY_SSL_HEADER="HTTP_X_FORWARDED_PROTO,https".
_proxy_hdr = os.getenv('DJANGO_SECURE_PROXY_SSL_HEADER', '').strip()
if _proxy_hdr:
    try:
        name, value = [p.strip() for p in _proxy_hdr.split(',', 1)]
        SECURE_PROXY_SSL_HEADER = (name, value)
    except ValueError:
        # Misconfiguration is ignored; Django will treat requests as-is.
        pass

# Prevent the browser from MIME-type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking protection
X_FRAME_OPTIONS = 'DENY'

# Use secure cookies over HTTPS (default True in prod, can be overridden in env)
SESSION_COOKIE_SECURE = os.getenv('DJANGO_SESSION_COOKIE_SECURE', str(not DEBUG)).lower() == 'true'
CSRF_COOKIE_SECURE = os.getenv('DJANGO_CSRF_COOKIE_SECURE', str(not DEBUG)).lower() == 'true'

# HttpOnly flags help mitigate XSS for session/CSRF cookies
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Set a conservative Referrer-Policy
SECURE_REFERRER_POLICY = 'same-origin'

# Note: SECURE_BROWSER_XSS_FILTER has been removed in modern Django and is ignored
# by most browsers. Prefer CSP (configured via ContentSecurityPolicyMiddleware).

# Optionally set CSRF trusted origins via env (comma-separated URLs)
_csrf_trusted = [o.strip() for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
if _csrf_trusted:
    CSRF_TRUSTED_ORIGINS = _csrf_trusted
